### ISSUE TITLE
 Week 3 / MAKEME.md

### ISSUE THREAD

**Issue by rabrad** [HackYourFuture/JavaScript3#370]
Hi, 
In section 3.1 Preparation, 
The external links of: 
- try...catch
- async/await
are missing.

**Comment by remarcmij** [comment]
Hi Rabie, they seem to work for me. Can you provide a bit more detail about what is happening when you click these links?

**Comment by rabrad** [comment]
Both are working now. 
I can't explain but both links were broken yesterday.

**Comment by remarcmij** [comment]
Okay, I will close this issue. But thanks for reporting.
